---
driver:
  name: ec2
  region: eu-central-1

provisioner:
  name: shell

platforms:
  - name: ubuntu-16.04
    driver:
      image_id: 
    transport:
      username: ubuntu

verifier:
  name: inspec

suites:
  - name: default